
  CREATE TABLE "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTNI_ZADACI" 
   (	"TASK_ID" NUMBER, 
	"PROJ_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(400 BYTE), 
	"TASK_NAME" VARCHAR2(960 BYTE), 
	"POCETAK" DATE, 
	"ZAVRSETAK" DATE, 
	"KREIRAO" VARCHAR2(256 BYTE), 
	"DATUM_KREIRANJA" DATE, 
	"ZADNJE_IZMJENIO" VARCHAR2(256 BYTE), 
	"DATUM_ZADNJE_IZMJENE" DATE
   );

  CREATE UNIQUE INDEX "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTNI_ZADACI_U1" ON "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTNI_ZADACI" ("TASK_ID", "PROJ_ID");

