/* $Header: $
============================================================================+
File Name   : XXDL_OE_LINES_ALL.sql
Description : Log table for sales order lines migration

History     :
v1.0 19.01.2023 ZKOVAC: Initial creation
============================================================================+*/
create table XXDL_OE_LINES_ALL
(
    "LINE_ID" NUMBER NOT NULL, 
	"HEADER_ID" NUMBER NOT NULL, 
    "ORDER_NUMBER" VARCHAR2(30 BYTE),
    "TRANSACTIONAL_CURR_CODE" VARCHAR2(5 BYTE), 
	"BU_NAME" VARCHAR2(240 BYTE), 
	"BUYING_PARTY_NAME" VARCHAR2(100 BYTE), 
    "ACCOUNT_NUMBER" VARCHAR2(100 BYTE),
	"BILL_TO_USE_ID" NUMBER, 
	"SHIP_TO_USE_ID" NUMBER, 
	"LINE_NUMBER" VARCHAR2(5), 
	"SHIPMENT_NUMBER" VARCHAR2(5), 
    "ITEM_NUMBER" VARCHAR2(20 BYTE),
    "ITEM_ID" NUMBER,
    "UOM" VARCHAR2(10 BYTE),
	"ORDERED_QUANTITY" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"SELLING_PRICE_CONV" NUMBER, 
	"SHIP_FROM_ORG_CODE" VARCHAR2(4), 
    "REQUEST_DATE" DATE,
    "PROMISE_DATE" DATE,
    "SHIP_DATE" DATE,
    "SALESREP_NAME" VARCHAR2(100),
    "SALESREP_ID" NUMBER,
    "TAX_CODE" VARCHAR2(100),
    "NALOG_IZRADE" VARCHAR2(200),
    "KOORDINACIJA" VARCHAR2(100),
    "RADNI_NALOG" VARCHAR2(100),
    "ISPORUKA" VARCHAR2(100),
    "MT_GARAZNI" VARCHAR2(100),
    "KM_GARAZNI" VARCHAR2(100),
    "SATI_GARAZNI" VARCHAR2(100),
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CLOUD_HEADER_ID" NUMBER,
    "CLOUD_LINE_ID" NUMBER)
;


  CREATE UNIQUE INDEX "XXDL_OE_LINES_ALL_T1" ON "XXDL_OE_LINES_ALL" ("LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

--create synonym apps.XXDL_OE_LINES_ALL for xxdl.XXDL_OE_LINES_ALL;

/
EXIT;

