/* $Header: $
============================================================================+

File Name   : XXDL_POZ_SUPPLIER_BANK_ACC.sql
Description : Table creation script 


History     :
V1.0 03.10.2022 - Zoran Kovac - initial creation
============================================================================+*/

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

PROMPT XXDL_POZ_SUPPLIER_BANK_ACC;
--drop index XXDL_POZ_SUPPLIER_BANK_ACC_U1;
--drop table XXDL_POZ_SUPPLIER_BANK_ACC;

CREATE
  TABLE "XXDL_POZ_SUPPLIER_BANK_ACC"
  (
    EXT_BANK_ACCOUNT_ID NUMBER,
    BANK_NAME NUMBER,
    BANK_ADDRESS VARCHAR2(960),
    IBAN VARCHAR2(240),
    CURRENCY_CODE VARCHAR2(3),
    COUNTRY_CODE VARCHAR2(2),
    BANK_ACCOUNT_NUM VARCHAR2(240),
    START_DATE VARCHAR2(35),
    END_DATE	 VARCHAR2(35),
    SIWFT_CODE  VARCHAR2(35),
    VENDOR_ID  NUMBER ,
    PARTY_ID NUMBER ,
    VENDOR_NAME VARCHAR2(240),
    SUPPLIER_NUMBER VARCHAR2(100),
    CREATION_DATE VARCHAR2(35),
    LAST_UPDATE_DATE VARCHAR2(35),
    TRANSF_CREATION_DATE DATE,
    TRANSF_LAST_UPDATE   DATE,
    CLOUD_IMPORTED VARCHAR2(1),
    CLOUD_IMPORT_MESSAGE VARCHAR2(4000),
    CLOUD_SITE_ASSIGNMENT VARCHAR2(1)
   );
  
  
    CREATE UNIQUE INDEX "XXDL_POZ_SUPPLIER_BANK_ACC_U1" ON "XXDL_POZ_SUPPLIER_BANK_ACC" ("EXT_BANK_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ;

EXIT;
/

