/* $Header: $
============================================================================+
File Name   : XXDL_ITEMS_UPDATE_MIG.sql
Description : Log table for items update

History     :
v1.0 27.01.2023 Marko Sladoljev: Initial creation
============================================================================+*/
drop table XXDL_ITEMS_UPDATE_MIG;

create table XXDL_ITEMS_UPDATE_MIG
(
	INVENTORY_ITEM_ID NUMBER NOT NULL ENABLE, 
	ORGANIZATION_ID NUMBER NOT NULL ENABLE, 
  SEGMENT1 VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	ORGANIZATION_CODE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
  ITEM_TYPE_ORG VARCHAR2(50),
  ITEM_TYPE_MAS VARCHAR2(50),
	PROCESS_FLAG VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	ERROR_MSG VARCHAR2(4000 BYTE), 
  WS_CALL_ID NUMBER,
	CREATION_DATE DATE NOT NULL ENABLE, 
	LAST_UPDATE_DATE DATE NOT NULL ENABLE
);

  CREATE UNIQUE INDEX XXDL_ITEMS_UPDATE_MIG_I1 ON XXDL_ITEMS_UPDATE_MIG (INVENTORY_ITEM_ID, ORGANIZATION_ID);
  CREATE INDEX XXDL_ITEMS_UPDATE_MIG_I2 ON XXDL_ITEMS_UPDATE_MIG (SEGMENT1);
  
EXIT;

