/* $Header: $
============================================================================+
File Name   : XXDL_HZ_CUST_ACCT_SITES.sql
Description : Log table for customer account sites migration to cloud

History     :
v1.0 09.09.2022 ZKOVAC: Initial creation
============================================================================+*/
create table XXDL_HZ_CUST_ACCT_SITES
(
    "CUST_ACCT_SITE_ID" NUMBER NOT NULL ENABLE, 
    "CUST_ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
    "PARTY_SITE_ID" NUMBER NOT NULL ENABLE, 
	"ATTRIBUTE4" VARCHAR2(240 BYTE), 
	"BILL_TO_FLAG" VARCHAR2(1 BYTE), 
	"SHIP_TO_FLAG" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(2 BYTE), 
	"ORG_ID" NUMBER, 
	"CLOUD_SET_ID" NUMBER, 
	"PROCESS_FLAG" VARCHAR2(1 BYTE), 
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CLOUD_CUST_ACCOUNT_ID" NUMBER,
	"CLOUD_PARTY_SITE_ID" NUMBER,
	"CLOUD_CUST_ACCT_SITE_ID" NUMBER,
	"CLOUD_PARTY_FISCAL_CODE" VARCHAR2(100),
	"CLOUD_TAX_PROFILE_ID" NUMBER,
	"CODE_ASSIGNMENT_ID" NUMBER
)
;


  CREATE UNIQUE INDEX "XXDL_HZ_CUST_ACCT_SITE_T1" ON "XXDL_HZ_CUST_ACCT_SITES" ("CUST_ACCT_SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

--create synonym apps.XXDL_HZ_CUST_ACCT_SITES for xxdl.XXDL_HZ_CUST_ACCT_SITES;

/
EXIT;

