
  CREATE TABLE "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTI" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BROJ" VARCHAR2(100 BYTE), 
	"NAZIV" VARCHAR2(960 BYTE), 
	"BUSINESS_UNIT" NUMBER, 
	"DATUM_POCETKA" DATE, 
	"DATUM_ZAVRSETKA" DATE, 
	"DATUM_ZATVARANJA" DATE, 
	"KREATOR" VARCHAR2(256 BYTE), 
	"DATUM_KREIRANJA" DATE, 
	"ZADNJE_AZURIRAO" VARCHAR2(256 BYTE), 
	"DATUM_ZADNJEG_AZURIRANJA" DATE
   );

  CREATE UNIQUE INDEX "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTI_U1" ON "XX_INTEGRATION_PROD"."XXDL_OA_PROJEKTI" ("ID");

