
  CREATE TABLE "XX_INTEGRATION_PROD"."XXDL_CURRENCY_RATES" 
   (	"EXCHANGE_RATE_NUMBER" NUMBER, 
	"DATE_OF_APPLICATION" VARCHAR2(10 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"UNIT" NUMBER, 
	"BUYING_RATE" NUMBER, 
	"MIDDLE_RATE" NUMBER, 
	"SELLING_RATE" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"ACTION" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"LAST_API_MESSAGE" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE)
   ) ;

  CREATE UNIQUE INDEX "XX_INTEGRATION_PROD"."XXDL_CURRENCY_RATES_U1" ON "XX_INTEGRATION_PROD"."XXDL_CURRENCY_RATES" ("DATE_OF_APPLICATION", "CURRENCY_CODE");

