/* $Header: $
============================================================================+
File Name   : XXDL_OE_HEADERS_ALL.sql
Description : Log table for sales order migration

History     :
v1.0 19.01.2023 ZKOVAC: Initial creation
============================================================================+*/
create table XXDL_OE_HEADERS_ALL
(
    "ORDER_NUMBER" VARCHAR2(40 BYTE), 
	"HEADER_ID" NUMBER NOT NULL ENABLE, 
    "TRANSACTIONAL_CURR_CODE" VARCHAR2(5 BYTE), 
	"BU_NAME" VARCHAR2(240 BYTE), 
	"BUYING_PARTY_NAME" VARCHAR2(100 BYTE), 
    "ACCOUNT_NUMBER" VARCHAR2(100 BYTE),
	"ORDER_TYPE" VARCHAR2(100 BYTE),
	"BILL_TO_USE_ID" NUMBER, 
	"SHIP_TO_USE_ID" NUMBER, 
	"BROJ_ZAKLJUCKA" VARCHAR2(100), 
	"DATUM_ZAKLJUCKA" VARCHAR2(100), 
	"KROVNI_UGOVOR" VARCHAR2(100),
	"BANK_ACCOUNT" VARCHAR2(200), 
	"MTR" VARCHAR2(100), 
	"PROJEKT" VARCHAR2(100), 
	"ATEST" VARCHAR2(100), 
	"PARITET" VARCHAR2(100), 
	"PRIVREMENA_LOKACIJA" VARCHAR2(100), 
	"REKLAMACIJA" VARCHAR2(100), 
	"KROVNI_NALOG" VARCHAR2(100), 
	"SALESREP_NAME" VARCHAR2(100), 
	"PAYMENT_TERM_CODE" VARCHAR2(100), 
	"CUST_PO_NUMBER" VARCHAR2(300), 
	"ORDERED_DATE" DATE,
	"REQUEST_DATE" DATE,
	"PROCES_FLAG" VARCHAR2(1),
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CLOUD_HEADER_ID" NUMBER)
;


  CREATE UNIQUE INDEX "XXDL_OE_HEADERS_ALL_T1" ON "XXDL_OE_HEADERS_ALL" ("HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

--create synonym apps.XXDL_OE_HEADERS_ALL for xxdl.XXDL_OE_HEADERS_ALL;

/
EXIT;

