
  CREATE TABLE "XX_INTEGRATION_PROD"."XXDL_EMP_CC_INTEGRATION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(50 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(600 BYTE), 
	"EMPLOYEE_DESCRIPTION" VARCHAR2(960 BYTE), 
	"FUSION_VALUE_SET_ID" NUMBER, 
	"STATUS" VARCHAR2(15 BYTE), 
	"MESSAGE" VARCHAR2(2000 BYTE), 
	"LAST_WS_CALL_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE
   ) ;

  CREATE UNIQUE INDEX "XX_INTEGRATION_PROD"."XXDL_EMP_CC_INTEGRATION_U1" ON "XX_INTEGRATION_PROD"."XXDL_EMP_CC_INTEGRATION" ("ID") ;

